tasks:
  - init: ./mvnw install
    command: java -jar target/*.jar
    name: Run PetClinic app

ports:
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - redhat.vscode-xml

jetbrains:
  intellij:
    plugins:
      - com.haulmont.jpab
    prebuilds:
      version: both
